### ISSUE TITLE
Placeholder property on TextField

### ISSUE THREAD

**Issue by super2ni** [s-bauer/office-ui-fabric-vue#33]
Hello,

It does not seem to be possible to have a placeholder on the TextField component?

Anyway, thank you for your hard work.

Denis

**Comment by s-bauer** [comment]
Thanks for reporting this! I'll add the placeholder at the weekend!

**Comment by mathis-m** [comment]
@s-bauer is fixed see #37

**Comment by s-bauer** [comment]
It's fixed, but not yet released to npm. I'll wait with the next release till #36 is finished.
