### ISSUE TITLE
Cannot use OfficeIcon

### ISSUE THREAD

**Issue by super2ni** [s-bauer/office-ui-fabric-vue#35]
**Describe the bug**
Hello there,
I am not really sure its is an issue, more a lack of understanding from me. I try to use the OfficeIcon component but no icon visually appears. On the console, I can see this warning:

> The icon "binglogo" was used but not registered. See http://aka.ms/fabric-icon-usage for more information.

According to, I believe I have to run the **initializeIcons**, but I really do not understand where I can do this.

**To Reproduce**
1. Add the OfficeIcon to your component template like this:
`<OfficeIcon :iconName="'ChromeClose'"/>`
2. You can see the following warning in the console and no icon visually:

> The icon "chromeclose" was used but not registered. See http://aka.ms/fabric-icon-usage for more information.

**Expected behavior**
I would like to see the icon :)

**Comment by s-bauer** [comment]
Thank's for opening that many issues. This really helps improve the library! I'll probably add to the OfficeIcon that it will initialize the icons itself when required.

Anyway, I probably forgot to export the `initializeIcons` function... I'm about to push a fix for that!

**Comment by s-bauer** [comment]
Fixed with [Version 0.1.12](https://www.npmjs.com/package/office-vue-fabric/v/0.1.12)
