### ISSUE TITLE
Allow setting of input type on TextField

### ISSUE THREAD

**Issue by alexandertrefz** [s-bauer/office-ui-fabric-vue#40]
It should be possible to set the type of the TextField to allow type="password" etc.

**Comment by s-bauer** [comment]
Right, there is a [PR pending](https://github.com/s-bauer/office-ui-fabric-vue/pull/39/files) (I'll merge it today hopefully), which allows setting all properties to the input / textarea.

**Comment by alexandertrefz** [comment]
Ah, I didn't see that one. Great :)
